-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "length_mm" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "thickness_mm" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "width_mm" INTEGER NOT NULL DEFAULT 300;
